import { useLayoutEffect } from 'react';
import { useLocation, useNavigationType } from 'react-router-dom';

const USER_INTENT_EVENTS = [
	'touchstart',
	'pointerdown',
	'wheel',
	'keydown',
] as const;

// On mobile, the compositor can carry the previous page's scroll offset
// across an SPA navigation. It manifests in two ways, both of which
// must be handled:
//
// 1. Stale paint: the main thread reads scrollY=0 but the content layer
//    is painted at the old offset. A plain scrollTo(0,0) is a no-op
//    (no offset change, nothing reaches the compositor), so force a
//    real change: nudge to 1px, then settle at 0 next frame.
// 2. Late sync-back: the stale offset is written back into the main
//    thread as a genuine scroll (fires a scroll event) after our reset
//    already ran. Hold the scroll at the top until the first real user
//    input, then get out of the way.
export const ScrollToTop = () => {
	const { key } = useLocation();
	const navigationType = useNavigationType();

	useLayoutEffect(() => {
		if (navigationType === 'POP') return;

		// (1) Forced compositor resync.
		window.scrollTo(0, 1);
		const raf = requestAnimationFrame(() => {
			window.scrollTo(0, 0);
		});

		// (2) Guard against the late sync-back. The >1 check ignores the
		// scroll events generated by our own 1px nudge.
		const onScroll = () => {
			if (window.scrollY > 1) window.scrollTo(0, 0);
		};
		const release = () => {
			window.removeEventListener('scroll', onScroll);
			for (const e of USER_INTENT_EVENTS)
				window.removeEventListener(e, release);
		};
		window.addEventListener('scroll', onScroll);
		for (const e of USER_INTENT_EVENTS)
			window.addEventListener(e, release, { passive: true });

		return () => {
			cancelAnimationFrame(raf);
			release();
		};
	}, [key, navigationType]);

	return null;
};
