name: Build & Deploy Docker Image

on:
    workflow_dispatch: {}
    workflow_call:
        secrets:
            DIGITALOCEAN_ACCESS_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DO Container Registry
              run: doctl registry login

            - name: Write server secrets to .env.production
              run: |
                  echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> server/.env.production
                  echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> server/.env.production

            - name: Build Docker image
              run: |
                  docker build \
                    --build-arg GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} \
                    -t registry.digitalocean.com/heirloom-shop/node-app:latest .

            - name: Push Docker image
              run: docker push registry.digitalocean.com/heirloom-shop/node-app:latest
